// Vocabulary battery: every phrase family must fire on realistic variants
// (positives) and stay silent on academic lookalikes (negatives).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { scanText } from '../js/core/detect.js';

// [text, expected ruleId, minimum severity expected to be reported]
const POSITIVES = [
  // --- assistant self-reference ---
  ['As an AI language model, I cannot assist with that.', 'ai-self-ref'],
  ['As an AI assistant, my role here is limited.', 'ai-self-ref'],
  ['As a language model, I lack real-world grounding.', 'ai-self-ref'],
  ['As an artificial intelligence, I process text statistically.', 'ai-self-ref'],
  ['As a large language model, I have inherent limitations.', 'llm-self-ref'],
  ["I'm an AI and cannot form opinions.", 'i-am-ai'],
  ['I am ChatGPT, a model developed by OpenAI.', 'i-am-ai'],
  ["I don't have personal opinions on this controversy.", 'no-opinions'],
  ['I do not have feelings about the outcome.', 'no-opinions'],
  // --- knowledge cutoff ---
  ['My knowledge cutoff is April 2023, so newer work is missing.', 'cutoff'],
  ['As of my last update, this benchmark did not exist.', 'cutoff'],
  ['I was last trained on data through 2024.', 'cutoff'],
  ['My training data only goes up to September 2021.', 'cutoff'],
  ["I don't have access to real-time information.", 'cutoff'],
  // --- refusals ---
  ['I cannot browse the internet to verify the claim.', 'cannot-fulfill'],
  ['I am unable to access external databases directly.', 'cannot-fulfill'],
  ["I can't open the attachment you provided.", 'cannot-fulfill'],
  ["I'm sorry, but I can't help with that request.", 'sorry-but-i'],
  // --- openers / hand-offs ---
  ['Certainly! Here is the revised abstract.', 'chat-opener'],
  ["Sure, here's an improved version of the paragraph.", 'heres-your'],
  ['Of course! I can rewrite the section for clarity.', 'chat-opener'],
  ["Got it! I've updated the introduction accordingly.", 'chat-opener'],
  ['Understood! Let me revise the methods section.', 'chat-opener'],
  ['No problem! Below is the corrected proof.', 'chat-opener'],
  ['Here is your summary of the related work.', 'heres-your'],
  ["Here's the final version of the conclusion.", 'heres-your'],
  ['Here is the complete rewritten related-work section.', 'heres-your'],
  ["I've updated the results section to address the comment.", 'ive-updated'],
  ['I have now incorporated all the suggested changes.', 'ive-updated'],
  ['As you requested, the notation has been simplified.', 'ive-updated'],
  ['Here you go: the polished abstract.', 'here-you-go'],
  // --- closers ---
  ['I hope this helps with your submission!', 'hope-helps'],
  ['Hope this helps!', 'hope-helps'],
  ['Let me know if you need anything else.', 'let-me-know'],
  ['Please let me know your thoughts on the revision.', 'let-me-know'],
  ['Feel free to adjust the wording to match your style.', 'feel-free'],
  ['Feel free to reach out with any questions.', 'feel-free'],
  ['Would you like me to shorten the abstract?', 'would-you-like'],
  ['Do you want me to add more citations?', 'would-you-like'],
  ['Is there anything else I can help with today?', 'anything-else'],
  ["I'm happy to help with further revisions.", 'glad-help'],
  ['Glad I could help!', 'glad-help'],
  // --- replies ---
  ["You're absolutely right, the sign was flipped.", 'youre-right'],
  ['You are right that the bound is loose.', 'youre-right'],
  ['Thank you for pointing that out.', 'thanks-pointing'],
  ['Thanks for sharing the draft.', 'thanks-pointing'],
  ['Thank you for your feedback on the proof.', 'thanks-pointing'],
  ['Apologies for the confusion in the earlier draft.', 'apologize-confusion'],
  ['I apologize for the oversight.', 'apologize-confusion'],
  ['Good catch! Fixed in the equation.', 'good-catch'],
  ['Great question! The intuition is as follows.', 'good-catch'],
  ['I understand your concern about novelty.', 'understand-concern'],
  ['As per your request, the related work is expanded.', 'as-per-request'],
  ['Per your instructions, Table 2 was removed.', 'as-per-request'],
  // --- chat UI artifacts ---
  ['Regenerate response', 'chatgpt-ui'],
  ['ChatGPT can make mistakes. Check important info.', 'chatgpt-ui'],
  ['Copy code', 'chatgpt-ui'],
  ['Model: GPT-4o', 'chatgpt-ui'],
  // --- review-only chat phrases (medium) ---
  ['If you have any further questions, just ask.', 'if-questions'],
  ["Don't hesitate to reach out.", 'dont-hesitate'],
  ['This section was generated by ChatGPT.', 'ai-attribution'],
  ['The abstract was drafted using a large language model.', 'ai-attribution'],
  // --- placeholders ---
  ['[insert citation here]', 'placeholder-bracket'],
  ['[TODO: add ablation study]', 'todo-bracket'],
  ['See Figure X for the architecture.', 'figure-x'],
  ['Results appear in Table ?? below.', 'figure-x'],
  ['Insert figure here.', 'insert-figure'],
  ['Previous work (Author, Year) shows this.', 'author-year-placeholder'],
  ['The claim is well known [citation needed].', 'citation-needed'],
];

// LaTeX-only positives
const TEX_POSITIVES = [
  ['We build on \\cite{ref1} for the encoder.', 'generic-cite-key'],
  ['Prior art \\citep{placeholder} agrees.', 'generic-cite-key'],
  ['The **key idea** is sparsity.', 'md-bold'],
  ['See the [docs](https://example.com/guide) for setup.', 'md-link'],
  ['Performance improved significantly 🚀 across tasks.', 'emoji-tex'],
];

// Academic lookalikes: NO auto-selected (pre-checked) finding may fire.
const NEGATIVES = [
  'We hope this helps practitioners adopt our method.',
  'Sure enough, the results confirm the hypothesis.',
  'Of course, this assumption may fail in practice.',
  'It is absolutely right to question this assumption.',
  'Survival analysis handles right-censored data; observations are right-censored when the event is unobserved.',
  'Most participants were right-handed.',
  'Feel free to skip the appendix on first reading.',
  'The model cannot browse the web, by design, since it has no tools.',
  'As an aside, the proof generalizes to the non-convex case.',
  'As an air-quality model, CMAQ simulates pollutant transport.',
  'Here is a summary of our contributions.',
  'The theorem holds [12] and extends the bound of [Smith 2020].',
  'Copy code snippets are provided in the supplementary repository.',
  'Model: GPT-4 was evaluated against all baselines.',
  'Our approach delves into the geometry of loss landscapes.',
  'Thank you for reading.',
  'The response rate in the user survey was 62%.',
  'In this paper we present a game-theoretic analysis.',
  'The updated version of the dataset contains 2M examples.',
  'We are happy to release all code and checkpoints.',
];

for (const [text, ruleId] of POSITIVES) {
  test(`fires ${ruleId}: “${text.slice(0, 55)}”`, () => {
    const r = scanText(text, { filetype: 'txt' });
    assert.ok(r.findings.some((f) => f.ruleId === ruleId),
      `expected ${ruleId}; got ${JSON.stringify(r.findings.map((f) => f.ruleId))}`);
  });
}

for (const [text, ruleId] of TEX_POSITIVES) {
  test(`fires ${ruleId} (tex): “${text.slice(0, 55)}”`, () => {
    const r = scanText(text, { filetype: 'tex' });
    assert.ok(r.findings.some((f) => f.ruleId === ruleId),
      `expected ${ruleId}; got ${JSON.stringify(r.findings.map((f) => f.ruleId))}`);
  });
}

for (const text of NEGATIVES) {
  test(`silent on: “${text.slice(0, 60)}”`, () => {
    const r = scanText(text, { filetype: 'txt' });
    const selected = r.findings.filter((f) => f.selected);
    assert.equal(selected.length, 0,
      `false positive: ${JSON.stringify(selected.map((f) => [f.ruleId, f.match]))}`);
  });
}

// Sentence-level hard-wrap robustness for a sample of new rules
test('new rules match across hard-wrapped lines', () => {
  const t = 'I have now\nincorporated all the requested\nchanges. Do you want\nme to expand the appendix?';
  const r = scanText(t);
  const ids = r.findings.map((f) => f.ruleId);
  assert.ok(ids.includes('ive-updated'));
  assert.ok(ids.includes('would-you-like'));
});
